### ISSUE TITLE
Error during bundle install

### ISSUE THREAD

**Issue by geneowak** [orocos-toolchain/utilrb#22]
Hello guys,
Am very new to ruby on rails and am kinda new to programming (having done a bit C and C++). I am not sure if this is where to ask questions (as this is my first submission) but i really need someone to help me out.
I recently got really interested in rails and decided to learn and use it. I've downloaded books and tutorials but am yet to create my first app. Every time i try to create an app, all files are created until the part  of ***run bundle install***  where i get the following error...

>run  bundle install
>DL is deprecated, please use Fiddle*
>Fetching source index from https://rubygems.org/
>Retrying source fetch due to error (2/3): Bundler::Fetcher::CertificateFailureEr
>ror Could not verify the SSL certificate for https://rubygems.org/.
>There is a chance you are experiencing a man-in-the-middle attack, but most like
>ly your system doesn't have the CA certificates needed for verification. For inf
>ormation about OpenSSL certificates, see bit.ly/ruby-ssl. To connect without usi
>ng SSL, edit your Gemfile sources and change 'https' to 'http'.
>Retrying source fetch due to error (3/3): Bundler::Fetcher::CertificateFailureEr
>ror Could not verify the SSL certificate for https://rubygems.org/.
>There is a chance you are experiencing a man-in-the-middle attack, but most like
>ly your system doesn't have the CA certificates needed for verification. For inf
>ormation about OpenSSL certificates, see bit.ly/ruby-ssl. To connect without usi
>ng SSL, edit your Gemfile sources and change 'https' to 'http'.
>Could not verify the SSL certificate for https://rubygems.org/.
>There is a chance you are experiencing a man-in-the-middle attack, but most
>likely your system doesn't have the CA certificates needed for verification. For
>information about OpenSSL certificates, see bit.ly/ruby-ssl. To connect without
>using SSL, edit your Gemfile sources and change 'https' to 'http'.

I have tried to follow guides on how to solve the ssl error but i have not yet succeeded..
I have even tried these commands (shown with their responses);

>C:\Sites\readit>gem source -r https://rubygems.org
>source https://rubygems.org not present in cache

>C:\Sites\readit>gem source -a http://rubygems.org
>https://rubygems.org is recommended for security over http://rubygems.org

>Do you want to add this insecure source? [yn]  y
>http://rubygems.org added to sources

But i still get the same error when i try to create a new app....
I have the following versions installed;
*git version 1.9.4.msysgit.2*
*ruby 2.1.5*
*rails 4.1.8*
Someone please help me out.

**Comment by doudou** [comment]
I am sorry, but the only relation this repository has to your problem is that it is written using the Ruby language.

**Comment by geneowak** [comment]
OK, then where can i go for help??

**Comment by doudou** [comment]
Since your problem is with bundler, http://bundler.io/

**Comment by geneowak** [comment]
Thanks
